pipeline {
    agent any
    stages {
        stage('Build') {
            steps {
                sh 'mvn clean package'
            }
        }
        stage('Test') {
            steps {
                sh 'mvn test'
            }
        }
        stage('Docker Build & Run') {
            steps {
                sh 'docker build -t java-jenkins-docker:latest .'
                sh 'docker run --rm java-jenkins-docker:latest'
            }
        }
    }
}
