# Generated by Django 5.2.5 on 2025-08-07 07:24

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BuildJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('description', models.TextField(blank=True)),
                ('repository_url', models.URLField(blank=True)),
                ('branch', models.CharField(default='main', max_length=100)),
                ('status', models.CharField(choices=[('active', 'Active'), ('disabled', 'Disabled'), ('archived', 'Archived')], default='active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='Environment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('env_type', models.CharField(choices=[('development', 'Development'), ('staging', 'Staging'), ('production', 'Production'), ('testing', 'Testing')], max_length=20)),
                ('url', models.URLField(blank=True)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['env_type', 'name'],
            },
        ),
        migrations.CreateModel(
            name='BuildRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('build_number', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('success', 'Success'), ('failed', 'Failed'), ('aborted', 'Aborted')], default='pending', max_length=20)),
                ('commit_hash', models.CharField(blank=True, max_length=40)),
                ('commit_message', models.TextField(blank=True)),
                ('author', models.CharField(blank=True, max_length=100)),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('duration', models.DurationField(blank=True, null=True)),
                ('log_output', models.TextField(blank=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='build_runs', to='dashboard.buildjob')),
            ],
            options={
                'ordering': ['-build_number'],
                'unique_together': {('job', 'build_number')},
            },
        ),
        migrations.CreateModel(
            name='Deployment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('deploying', 'Deploying'), ('success', 'Success'), ('failed', 'Failed'), ('rolled_back', 'Rolled Back')], default='pending', max_length=20)),
                ('deployed_by', models.CharField(blank=True, max_length=100)),
                ('deployed_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('build_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deployments', to='dashboard.buildrun')),
                ('environment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deployments', to='dashboard.environment')),
            ],
            options={
                'ordering': ['-deployed_at'],
                'unique_together': {('build_run', 'environment')},
            },
        ),
    ]
