pipeline {
    agent any
    environment {
        DOCKERHUB_CREDENTIALS = credentials('dockerhub-creds') // Jenkins credential ID
        DOCKER_IMAGE = "theshubhamgour/python-jenkins-docker"
    }
    stages {
        stage('Build') {
            steps {
                sh 'python -m py_compile app.py'
            }
        }
        stage('Test') {
            steps {
                sh 'python -m unittest discover tests'
            }
        }
        stage('Docker Build') {
            steps {
                sh 'docker build -t "$DOCKER_IMAGE:latest" .'
            }
        }
        stage('Docker Push') {
            steps {
                sh 'echo "$DOCKERHUB_CREDENTIALS_PSW" | docker login -u "$DOCKERHUB_CREDENTIALS_USR" --password-stdin'
                sh 'docker push "$DOCKER_IMAGE:latest"'
            }
        }
        stage('Docker Run') {
            steps {
                sh 'docker run --rm "$DOCKER_IMAGE:latest"'
            }
        }        
    }
    post {
        always {
            cleanWs()
        }
        success {
            echo 'Pipeline completed successfully!'
        }
        failure {
            echo 'Pipeline failed!'
        }
    }
}